name: Slack SDK Enrichment
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: slack-raw
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: slack-enriched
    required: false
  - name: slack_token
    inputType: Secret
    description: ''
    defaultValue: slack_token
    required: true
  - name: redis_host
    inputType: FreeText
    description: ''
    defaultValue: redis-16017.c251.east-us-mz.azure.redns.redis-cloud.com
    required: true
  - name: redis_port
    inputType: FreeText
    description: ''
    defaultValue: 16017
    required: true
  - name: redis_password
    inputType: Secret
    description: ''
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
