name: slack-history-preprocessing
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: slack-raw-history
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: slack-raw
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
