name: Create embeddings
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw-text-chunks-2024-04-05-v2
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: embeddings
    required: false
  - name: consumergroup
    inputType: FreeText
    description: ''
    defaultValue: embeddings-v2
    required: false
  - name: OPENAI_API_KEY
    inputType: Secret
    defaultValue: OPENAI_API_KEY
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
